# PKGBUILD generated by pipman
# Python package author: {aut} <{authmail}>
pkgname={pkgname}
pkgver={pkgver}
pkgrel={pkgrel}
pkgdesc="{pkgdesc}"
arch=(any)
url="{url}"
license=("{license}")
makedepends=("python" "python-pip")
depends=({depends})

build() {{
    pip install --no-deps --target="{pack}" {pack}
}}

package() {{
    mkdir -p $pkgdir/usr/lib/python{pyversion}/site-packages/
    cp -r $srcdir/{pack}/* $pkgdir/usr/lib/python{pyversion}/site-packages/
}}
